### ISSUE TITLE
Can't create new user using CI3

### ISSUE THREAD

**Issue by jhob101** [ci-bonfire/Bonfire#1108]
Works fine when using CI2, on switching to CI3 and attempting to create a new user results in form validation errors on email, username and password fields:

`FIXME('form_validation_valid_password') FIXME('form_validation_unique') FIXME('form_validation_unique')`

Screenshot: http://hob.so/aqWu

**Comment by mwhitneysdsu** [comment]
I was not able to replicate this exact issue, but I did find a few missing lang file entries and added them in a857432dded60fed74db6c50b311948a7761a8c0. However, some updates have been made to the relevant areas since 0.7.2 was released, so, if you're using the release/master version of Bonfire, it may simply be that these issues have already been addressed in develop.

You may want to update your users module, /bonfire/libraries/BF_form_validation.php, and /application/language/english/bf_form_validation_lang.php from the develop branch.

If you have a users module in your application (to override some of the functionality), you may need to update the model and/or controller there, as well.

Finally, if you have /application/libraries/MY_form_validation.php with an override for valid_password() or unique(), they may need some changes (or you may just need to add the associated language entries).

BF_form_validation's valid_password() method uses the following language entries: bf_form_valid_password, bf_form_valid_password_nums, bf_form_valid_password_syms, bf_form_valid_password_mixed_1, and bf_form_valid_password_mixed_2. The unique method uses bf_form_unique. These are all set in the /application/language/*/application_lang.php file.

**Comment by didiwijaya** [comment]
maybe the fault lies in bonfire/libraries which is not loaded. I have tried master branch and newest develop branch, but all the same, bonfire/libraries not loaded. 
For example : bonfire/libraries/BF_Form_validation, bonfire/libraries/Assets.
unique, valid_password, add_module_js, add_css can not be used.

please, give solution !

**Comment by mwhitneysdsu** [comment]
The Assets and form_validation libraries are autoloaded in Authenticated_Controller, which is extended by Admin_Controller, which is extended by the users Settings controller. Still, if these libraries are not loaded, you should get errors long before those pictured in your screenshot.

**Comment by mwhitneysdsu** [comment]
@didiwijaya your issue is unrelated, because errors would be generated before the screenshot shown in the original message.

**Comment by mwhitneysdsu** [comment]
If the two issues are related, this one should also be fixed by f8854b7678c4484c69337c3b3f108cf5296d1c2b as well.

**Comment by didiwijaya** [comment]
I think, this issues are related
