### ISSUE TITLE
Bonfire 0.7.3: Module Builder always gives error

### ISSUE THREAD

**Issue by kocil** [ci-bonfire/Bonfire#1119]
Dear Bonfire developer,

I tried to buiild a new module using the Module Builder.
Filled the module name, no database, it gave this error:

FIXME('form_validation_xss_clean')

Thank you 

CI version: 3.0.0
Bonfire version: 0.7.3

**Comment by mwhitneysdsu** [comment]
I'll have to check to determine whether xss_clean is still being used in Module Builder (if it is, it should be removed), but would recommend upgrading to 0.7.4 or to the develop branch (soon to be 0.7.5).

Additionally, for all issues related to Module Builder, it helps to know what settings were chosen for the module, since some errors are definitely determined by what Module Builder is trying to do.

**Comment by mwhitneysdsu** [comment]
Sorry, I got ahead of myself by a version. The develop branch is soon to be 0.7.4...
