### ISSUE TITLE
Problem with getting CI_ENV

### ISSUE THREAD

**Issue by marzsman** [ci-bonfire/Bonfire#1132]
On my local server setting the environment with CI_ENV worked perfectly. But when I test this on my server this wasn't working anymore.

It looks like the mod rewrite is adding a REDIRECT_ prefix for each redirect.
In my PHP variables I now have these variables

    _SERVER["REDIRECT_REDIRECT_CI_ENV"]	testing
    _SERVER["REDIRECT_REDIRECT_STATUS"]	200
    _SERVER["REDIRECT_CI_ENV"]	testing

So this check is not working for me

    define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');

I can add the REDIRECT_CI_ENV to make it work but isn't there any other cleaner solution?

**Comment by mwhitneysdsu** [comment]
How are you setting the variable on your server?

A quick search brought up this stackoverflow thread which seems to be relevant:
http://stackoverflow.com/questions/3050444/when-setting-environment-variables-in-apache-rewriterule-directives-what-causes

Personally, I set my CI_ENV variable in a conf file with a SetEnv call, rather than an .htaccess file, but I understand that not everyone will have that option.

**Comment by marzsman** [comment]
Yes it's in my htaccess file, I don't have access to the conf file. 
I've seen the thread you mention (and many others :) ), it's exactly the same issue.

Now I'm using some conditionals with SetEnvIf to check on which server I am:

    SetEnvIf Host local\. CI_ENV=local
    SetEnvIf Host ^(beta\.) CI_ENV=testing
    SetEnvIf Host ^(www\.|default\.) CI_ENV=production

I extended the check in index with the variable REDIRECT_CI_ENV. 
It feels a bit hacky but it's working.
