### ISSUE TITLE
Check for config bonfire.installed in is_installed function

### ISSUE THREAD

**Issue by marzsman** [ci-bonfire/Bonfire#1135]
Shouldn't the function is_installed in installer_lib have a check for the $config['bonfire.installed'] = "1"; ?

On a production site I was updating, the home controller was always redirecting to the installer. Adding the extra check in is_installed fixed the issue.

**Comment by mwhitneysdsu** [comment]
The reason the installer_lib doesn't have a check for this config value is that the config value is supposed to prevent the installer_lib from being loaded by /application/hooks/App_hooks.php.

**Comment by marzsman** [comment]
Hmm, must have missed something in my update. I'll try to find out what's going wrong.

**Comment by marzsman** [comment]
There's also a check in application/Home.php which loads the installer_lib in the construct. Shouldn't this be removed then?

**Comment by mwhitneysdsu** [comment]
The /application/controllers/Home.php is intended to be replaced/modified as needed, but the basic functionality included in there should still work properly. My recommendation for most developers getting started with Bonfire would be to copy the controller to /application/modules/home/controllers/Home.php and make your changes there, because it makes it easier to keep things in sync with the repository here.

However, the problem here is the redirect you're seeing to the Install controller. This means that is_installed() is returning false, which you've more or less already figured out. What we don't seem to know is why it's returning false.

The $config['bonfire.installed'] check was added to App_hooks.php because it needed a method of checking which is available very early in the process. It also is intended in part to make it possible to remove the Installer_lib from production servers (right now I can't remember whether this is actually completely possible, yet, but I know you can remove the Install controller, and that is certainly recommended for production servers). We should consider replacing the first check in is_installed() with that one, but I do have an aversion to performing the same check twice (as would be the case if is_installed() were called from App_hooks).

The first check in is_installed() looks for a file in `APPPATH . 'config/installed.txt'`, which is created by Installer_lib->setup(). This was originally created as a shortcut to prevent running the rest of the checks in an installed environment, and your site would have to be missing this file to get redirected to the Install controller by the Home controller.

If the file is missing, it goes on to looks for your database configuration file. This may be an issue in a production environment if you meet the perfect storm of odd configurations, as it can fail on a valid installation if you intend to use APPPATH . 'config/database.php' as your production database configuration file, but also placed your development configuration file (or a file which can't work in production) in APPPATH . 'config/development/database.php' (and did not place a valid configuration file in APPPATH . 'config/production/database.php').

If it loaded the database configuration file, it checks to see if $db and $db['default'] were defined by the configuration file. If you don't have a 'default' database configuration, or the 'default' configuration's 'database' key is empty, this will return false.

Next, it attempts to load the database library, using the 'default' database configuration. If it can't find the 'users' table using the 'default' database configuration, it will return false.

Finally, it checks to make sure at least one row exists in the 'users' table, and, if it does not, it returns false.

If it gets through all of these checks, it returns true, and your Home controller won't redirect to the Install controller.

So, the most common reasons that the Installer_lib->is_installed() call would return false in an environment which would otherwise be a functional server:
- `/application/config/development/database.php` and/or `/application/config/database.php` exists but `/application/config/{ENVIRONMENT}/database.php` does not (or the ENVIRONMENT is not defined correctly) and the loaded database configuration file is not valid for the current environment (and not the one which would be loaded by CodeIgniter).
- No users exist in the database (note: while the database migrations create the users table, they do not add the admin user to the system; this has to be done manually or via the Installer_lib->setup() method)
- The user_model has been modified to use a different database, so the 'users' table does not exist and/or contains no users in the default database.

**Comment by marzsman** [comment]
For now I just removed the check in Home, this solves my problem, as it was only the Home controller that was redirecting. 
Thx for the explanation!
