### ISSUE TITLE
0.7.5 can't install

### ISSUE THREAD

**Issue by baby3873575** [ci-bonfire/Bonfire#1139]
Incorrect database name ''

**Comment by mwhitneysdsu** [comment]
https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/installation.md

Check your database configuration. The installation docs above have more information, as well as the CodeIgniter documentation: http://www.codeigniter.com/user_guide/database/configuration.html

**Comment by baby3873575** [comment]
sure, I have done that of course. It works on branch 0.7.4 & bootstrap3 but failed at 0.7.5dev & develop

**Comment by mwhitneysdsu** [comment]
I'm assuming this is a new installation using 0.7.5-dev.

Was 0.7.5-dev downloaded in the last 3 hours (since 0a266511c922bda224548da4ee02bf62a903b746 was committed to fix an error with the writable directory check on Windows)?

I'm pretty sure there have been no other changes to the installer since 0.7.4 was released.

Is "Incorrect database name ''" the only error message you are receiving? If so, where/at what point are you getting that message?

**Comment by baby3873575** [comment]
Sorry, I have fixed this problem with providing both CI 2,3 if else blocks
in database settings. Looks like it doesn't run in CI 3.  Sorry for
disturbing...
2015/7/10 上午2:23 於 "Mat Whitney" <notifications@github.com> 寫道：

**Comment by mwhitneysdsu** [comment]
0.7.x should work under CI3 if you follow the directions in the [CI3 upgrade doc](https://github.com/ci-bonfire/Bonfire/blob/0.7.5-dev/bonfire/docs/ci3.md)

However, if you are creating a new site for CI3, you're probably better off using 0.8.x, which comes with CI3 installed by default. 0.8.0 is in the master branch, 0.8.1 is in the develop branch. You can still use CI2 in 0.8.x, but you have to follow the directions in the [CI2 upgrade doc](https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/ci2.md) to get CI2 working.

And yes, you have to change some of your config files when going from one version of CI to the other, though the default config files in Bonfire 0.7.4+ are setup to work with both versions.
