### ISSUE TITLE
is is_unique a right name?

### ISSUE THREAD

**Issue by FrankMN** [ci-bonfire/Bonfire#1183]
in BF_Model, a function called is_unique but it is used to check existence...

**Comment by mwhitneysdsu** [comment]
I believe this is similar to [CodeIgniter's is_unique validation rule](http://www.codeigniter.com/user_guide/libraries/form_validation.html#rule-reference). The basic idea would be to check whether a value which you intend to add to the database (via update or insert) already exists in the database, essentially determining whether the value is unique.

**Comment by FrankMN** [comment]
```
        if ($query && $query->num_rows() == 0) {
            return true;
        }
```
this code fragment within is_unique uses num_rows() == 0 as condition, but I think if check whether a field/value is unique, should use 1, say the field/value only has one match.

**Comment by mwhitneysdsu** [comment]
After you insert the data, you will have num_rows() + 1 rows with that field/value combination. This is a helper method for validation. If we change the method in any way other than to fix an actual error, it will be to deprecate it, since it serves no real purpose when the unique and is_unique validation rules already exist.

**Comment by lonnieezell** [comment]
The logic is correct, though. Say you have a user with email 'x'. We want to make sure that is a unique user - in other words, that no users with an email 'X' exist in the database. So the function tries to find a match. If it does, if num_rows() is > 0, then it's NOT a unique item since one already exists. However, if num_rows() == 0, then what you want to insert into the database is unique.

However, I agree with Mat - this should be deprecated since it exists in CI.

**Comment by FrankMN** [comment]
I got it, thanks you guys!
