### ISSUE TITLE
Error on refreshing a page with form

### ISSUE THREAD

**Issue by jhon100** [ci-bonfire/Bonfire#1205]
I just installed the 0.8.3 version and get an error when trying to refresh a page that has a form. The error occurs with the following sequence:
1 - Fill out a form field with an invalid value.
2 - Press the button to save.
3 - An error message is displayed (referring to the invalid value)
4 - reload the page.
5 - The following error message appears:
An Error Was Encountered
The action you have requested is not allowed. You either do not have access, or your login session has expired and you need to sign in again.

Occurs on any page with form, in the backend, frontend, modules created by the module generator and also in the user profile form on the frontend.

**Comment by mwhitneysdsu** [comment]
This is caused by CSRF protection in the form. The primary thing Bonfire has changed over CI's default behavior is to add "You either do not have access, or your login session has expired and you need to sign in again." to the error message, which should make it slightly easier to determine the cause of the error. Bonfire also adds the ability to ignore CSRF verification for specific controllers without disabling it completely.

The reason this happens is that when you reload the page you re-send the previous POST data for that form, which contains an old value in the `csrf_token` field. The browser will usually prompt you about resending the information previously submitted in the form. If you were to change the information in the form and re-submit it, the updated token data included in the form would be submitted and this error would not occur.

You can disable CSRF protection site-wide with the `csrf_protection` setting in your config files, but this is generally not a good idea. Another alternative would be to set `csrf_regenerate` to false, but this reduces the security of the feature. For more details, see the CI user guide: https://codeigniter.com/user_guide/libraries/security.html#cross-site-request-forgery-csrf

**Comment by jhon100** [comment]
Thank you for the detailed answer... since I want to just allow the page to be reloaded without errors,  I came up with this, working for me:
```php
    public function csrf_show_error()
    {
        /*show_error('The action you have requested is not allowed. You either do not have access, or your login session has expired and you need to sign in again.');*/
		
		header('Location: ' . htmlspecialchars($_SERVER['REQUEST_URI']), TRUE, 200);
    }
```
As the page is reloaded, if the problem has been 'login session expired', the user is redirected and he can log in again.
