### ISSUE TITLE
Vulnerability Source Code Disclosure in "Bonfire/bonfire/modules/builder/views/files/"

### ISSUE THREAD

**Issue by abedzoubi26** [ci-bonfire/Bonfire#1217]
We have found vulnerability in CI Bonfire called "Source Code Disclosure" and after invesigation we did find that 90% of files in "Bonfire/bonfire/modules/builder/views/files/" can be accessed from web directly without any restrictions!

**Comment by nemurici** [comment]
I think that folder must not be accesible from the web, you must put the apache to point on the public folder...

**Comment by abedzoubi26** [comment]
Folder is already not accessible from web server but try to open this link please: 
{SERVER_NAME}/bonfire/bonfire/modules/builder/views/files/view_index.php

**Comment by jayjfletcher** [comment]
I get a 404. Your server is not set up correctly. Set your server root to
the public folder.

**Comment by mwhitneysdsu** [comment]
Please read the documentation regarding installing Bonfire on your site:
https://github.com/ci-bonfire/Bonfire/blob/develop/bonfire/docs/start_here/installation.md

If you do find a security issue, please contact lonnie@newmythmedia.com and/or mwhitney@mail.sdsu.edu, rather than posting it directly to GitHub as an issue. We will do our best to fix any security issues as quickly as possible, but I don't think many people would appreciate having a vulnerability posted publicly before anyone has had a chance to fix it. While I do check GitHub on a regular basis, there are times when I can't do so as often as I would like, and, if this had been a vulnerability, I wouldn't have even seen it for a week.

You might also want to consider removing the builder module (at least the `controllers` and `views` directories in the builder module) from your production site. It's a module I would generally only consider using on a development site, anyway.
