### ISSUE TITLE
Mobile nav not functioning properly

### ISSUE THREAD

**Issue by fjmorgan** [ci-bonfire/Bonfire#1240]
The mobile nav in admin is not working from Safari on iOS in v. 0.8.3.  Clicking the hamburger opens the menu but selecting any link within it simply collapses the menu without taking the user to the link.  It works fine on desktop with the browser reduced to mobile size, but on the mobile device itself it will not work.

**Comment by fjmorgan** [comment]
Sorry, this did not turn out to be a Bonfire issue.  It is a known issue with Bootstrap.  Applied this fix and it is resolved: http://stackoverflow.com/questions/17435359/bootstrap-collapsed-menu-links-not-working-on-mobile-devices

**Comment by yeshansachithak** [comment]
Ci-Bonfire still does have the issue. Due to the OLD version of bootstrap 2.3.2. However, I have fixed the issue with a simple CSS. 

**public/themes/admin/header.php**
`Assets::add_css(array(
    'bootstrap.css',
    'bootstrap-responsive.css',
    'fixmobile.css',//My custom CSS file
));`

**public/themes/admin/css/fixmobile.css**
`/*Fix mobile issue - 16072018*/
.dropdown-backdrop {
    display: none !important;
}`

Hope helps someone. Thanks!
