### ISSUE TITLE
old state and country db tables

### ISSUE THREAD

**Issue by jayjfletcher** [ci-bonfire/Bonfire#1245]
Hello,
I noticed that in migration 6 that the state and country tables were dropped.

Yet after a fresh bonfire install those tables are still there.

Any idea what may be causing the tables to not be dropped? 
Or did I miss that they were re-added somewhere else?

Thanks in advance!

**Comment by mwhitneysdsu** [comment]
There are any number of reasons that MySQL might decide not to drop a table when you tell it to do so, usually because it thinks the table is in use. It seems likely that the checks to determine that the tables exist before they are dropped or (in the case of the states table) the query to copy the data is preventing the table(s) from being dropped.

The tables are not added by a later migration.

**Comment by jayjfletcher** [comment]
Thank you mwhitneysdsu!
