### ISSUE TITLE
Layout-file for register-page

### ISSUE THREAD

**Issue by ColdIce1** [ci-bonfire/Bonfire#670]
So, we already got a layout file for login.php, but why not register.php?
Some users may want to completely lockdown their webpage down to login & register view with custom design...

**Comment by jkkenzie** [comment]
I dont understand this part:
"If you create a view in your theme it will override the default:
bonfire/themes/theme_name/users/users/register.php"

My theme is in public/themes/default/users/register.php and its not working. it loads for a long time and i think i had to change the max_nesting_level in php to see it completes processing. Even overriding my own module view on the themes folder is not working at all.

**Comment by mwhitneysdsu** [comment]
I would recommend starting with something very simple in `public/themes/default/users/register.php` (assuming you're using the default theme) just to ensure that it's loading the view.

In the case of your own modules, it depends on how you're loading the view, but mine work with `public/themes/{theme_name}/{module_name}/{optional_path_in_view_directory/}{view_name}.php`

The biggest issues tend to be making sure you don't add a `views` directory to your theme directory and that you include the module name when loading the view.

**Comment by jkkenzie** [comment]
mwhitneysdsu: idid what you said and My public/themes/default/users/register.php works without the echo isset($content) ? $content : Template::content(); , echo theme_view('header');theme_view('footer'); . I wanted it to work like the login.php that is in the public/default theme so as to load content from register.php in the bonfire users view.

**Comment by mwhitneysdsu** [comment]
I know this can be confusing, but `/public/themes/default/login.php` is not the same as `/public/themes/default/users/login.php`.

The first (without the `users/`) is a layout, which sets the template into which your views are rendered (the views are generally loaded in the location of the `Template::content()` call). The `Users` controller tells the `Template` library to use this layout when you use the `login()` method (usually via whatever your `LOGIN_URL` is set to) by calling `Template::render('login');` (instead of the usual `Template::render();`).

On the other hand, `/public/themes/default/users/login.php` should be a themed version of `/bonfire/modules/users/views/login.php`. This is a view which contains the login form itself. It does not load the header/footer and does not include calls to `Template::message()` or `Template::content()`.

The only other layout that's likely to be as confusing as the `login` layout is the `index` layout, but in both cases the layout is in the root of the theme directory (`/public/themes/default/`), while the view(s) are in sub-directories (`/public/themes/default/users/`).

When you want to override a view from one of the Bonfire modules, it's best practice to start by creating the directory named for the module (in your theme's directory), then copy the view(s) from the module's `views` directory into the new directory in your theme. Once that's done, you can customize the view(s) as needed, but I would recommend being very careful about what you change, because some parts of the view may be functionally required. For instance, if you change the name of a field in a form (or remove a field), it's possible that the form will no longer work properly.

**Comment by jkkenzie** [comment]
whew! Thanks for taking time to explain this.

**Comment by cosmomathieu** [comment]
Is this feature documented anywhere? I couldn't seem to find it in the documentations.
